back to normal

diff --git a/.github/workflows/nextjs.yml b/.github/workflows/nextjs.yml
--- a/.github/workflows/nextjs.yml
+++ b/.github/workflows/nextjs.yml
@@ -35,21 +35,21 @@ jobs:
         uses: actions/checkout@v4
       - name: Detect package manager
         id: detect-package-manager
-        # run: |
-        #   if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-        #     echo "manager=yarn" >> $GITHUB_OUTPUT
-        #     echo "command=install --legacy-peer-deps" >> $GITHUB_OUTPUT
-        #     echo "runner=yarn" >> $GITHUB_OUTPUT
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+            echo "command=install --legacy-peer-deps" >> $GITHUB_OUTPUT
+            echo "runner=yarn" >> $GITHUB_OUTPUT
             exit 0
-            [ -f "${{ github.workspace }}/package.json" ]; then
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
             echo "manager=npm" >> $GITHUB_OUTPUT
             echo "command=ci --legacy-peer-deps" >> $GITHUB_OUTPUT
             echo "runner=npx --no-install" >> $GITHUB_OUTPUT
             exit 0
-          # else
-          #   echo "Unable to determine package manager"
-          #   exit 1
-          # fi
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v4
         with:
